class UserData:
    UserName = '',
    FirstName = '',
    MiddleName = '',
    LastName = '',
    Email = '',
    PhoneNumber = '',
    Password = '',
    Age = '',
    Gender = '',
    ProfilePicture = '',
